In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

### Step 1: Import Data

The "real_estate_valuation_data_set.csv" file saves the market historical data of real estate valuation of a Chinese city. The variable information is as follows

| Variable Name | Role | Type | Description | Units | 
|:--|:--|:--|:--|:--|
|No|ID|Integer||||
|X1 transaction date|Feature|Continuous|for example, 2013.250=2013 March, <br>2013.500=2013 June, etc.||
|X2 house age|Feature|Continuous||year|
|X3 distance to the <br>nearest metro station|Feature|Continuous||meter|
|X4 number of <br>convenience stores|Feature|Integer|number of convenience stores in the<br> living circle on foot|integer|
|X5 latitude|Feature|Continuous|geographic coordinate, latitude|degree|
|X6 longitude|Feature|Continuous|geographic coordinate, longitude|degree|
|Y house price of<br> unit area|Target|Continuous|10000 Chinese Yuan per <br>square metre|10000 CNY/<br>square metre|

In [2]:
# Read the data with pandas
real_estate = pd.read_csv("real_estate_valuation_data_set.csv", index_col=0)

In [3]:
# Show the first five rows of the data
real_estate.head()

,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
No,,,,,,,
1,2012.917,32.0,84.87882,10,24.98298,121.54024,2.53
2,2012.917,19.5,306.59470,9,24.98034,121.53951,2.81
3,2013.583,13.3,561.98450,5,24.98746,121.54391,3.15
4,2013.500,13.3,561.98450,5,24.98746,121.54391,3.65
5,2012.833,5.0,390.56840,5,24.97937,121.54245,2.87

In [4]:
# Get the number of instances and features
row_num = real_estate.shape[0]
col_num = real_estate.shape[1]

In [5]:
row_num, col_num

(414, 7)

In [6]:
# Get the input variables X with features from X1 to X6.
X = np.array(real_estate.iloc[:,:6].values)

In [7]:
X.shape

(414, 6)

In [8]:
X

array([[2012.917  ,   32.     ,   84.87882,   10.     ,   24.98298,
         121.54024],
       [2012.917  ,   19.5    ,  306.5947 ,    9.     ,   24.98034,
         121.53951],
       [2013.583  ,   13.3    ,  561.9845 ,    5.     ,   24.98746,
         121.54391],
       ...,
       [2013.25   ,   18.8    ,  390.9696 ,    7.     ,   24.97923,
         121.53986],
       [2013.     ,    8.1    ,  104.8101 ,    5.     ,   24.96674,
         121.54067],
       [2013.5    ,    6.5    ,   90.45606,    9.     ,   24.97433,
         121.5431 ]])

In [9]:
# Get the target values y
y = np.array(real_estate.iloc[:,6].values)

In [10]:
y.shape

(414,)

In [11]:
y

array([2.53, 2.81, 3.15, 3.65, 2.87, 2.14, 2.69, 3.11, 1.25, 1.47, 2.76,
       3.87, 2.62, 1.59, 2.29, 3.37, 4.67, 2.49, 2.82, 3.18, 1.95, 3.44,
       1.64, 3.19, 2.59, 1.8 , 3.75, 2.24, 3.13, 3.81, 1.47, 1.67, 2.28,
       3.29, 3.67, 1.82, 1.53, 1.69, 3.18, 3.08, 1.06, 1.21, 2.31, 2.27,
       3.59, 2.55, 2.8 , 4.1 , 0.89, 0.88, 2.95, 1.38, 1.8 , 2.59, 3.45,
       0.91, 2.79, 3.57, 1.51, 2.83, 1.42, 4.21, 1.85, 3.67, 1.69, 2.95,
       3.38, 3.79, 2.41, 2.8 , 3.93, 2.72, 2.42, 1.33, 3.63, 1.97, 2.45,
       1.71, 1.99, 1.77, 2.69, 2.45, 3.21, 1.18, 2.91, 3.39, 1.8 , 1.22,
       3.2 , 1.69, 3.03, 2.88, 1.45, 1.07, 2.73, 3.45, 3.97, 2.31, 3.4 ,
       4.15, 2.55, 2.19, 3.63, 3.05, 2.03, 4.73, 3.14, 1.77, 2.27, 1.89,
       3.44, 2.63, 1.54, 0.51, 3.55, 3.09, 0.81, 0.87, 2.04, 3.97, 2.09,
       3.2 , 2.17, 3.03, 3.83, 3.24, 4.19, 3.67, 4.05, 2.73, 2.5 , 2.05,
       2.5 , 2.63, 2.81, 1.39, 3.12, 3.16, 2.9 , 2.83, 3.43, 1.93, 2.5 ,
       2.67, 1.89, 3.03, 3.48, 2.88, 3.01, 2.65, 3.23, 2.98, 1.93, 2.73,
       1.38, 1.04, 1.22, 2.37, 2.63, 2.49, 3.85, 2.64, 0.77, 3.7 , 3.68,
       2.04, 4.91, 2.89, 2.49, 1.57, 0.96, 3.92, 3.87, 2.34, 3.01, 2.43,
       1.28, 2.8 , 2.45, 2.84, 1.03, 3.73, 1.57, 1.25, 1.45, 1.43, 1.71,
       1.47, 2.95, 1.37, 2.82, 2.52, 2.85, 3.29, 1.95, 2.31, 2.44, 3.21,
       2.61, 2.11, 1.7 , 3.06, 2.1 , 3.07, 1.77, 1.43, 2.93, 2.28, 1.75,
       2.73, 3.48, 2.9 , 2.07, 3.87, 1.39, 3.21, 2.65, 2.72, 2.92, 2.68,
       5.22, 2.57, 3.23, 2.82, 3.07, 3.27, 0.85, 2.68, 3.11, 1.27, 2.23,
       0.98, 1.16, 2.16, 1.59, 2.62, 4.13, 2.6 , 2.71, 1.98, 1.92, 2.76,
       2.23, 3.21, 1.45, 2.72, 2.71, 1.54, 1.49, 1.  , 2.  , 0.92, 3.51,
       1.73, 3.45, 1.16, 1.77, 2.93, 4.22, 1.92, 2.05, 1.63, 3.53, 2.11,
       2.71, 2.54, 1.58, 2.74, 2.67, 1.53, 7.83, 1.77, 2.7 , 1.95, 2.73,
       3.31, 2.27, 1.85, 2.93, 2.07, 3.03, 2.99, 1.71, 1.57, 2.29, 3.69,
       3.75, 2.19, 3.4 , 2.97, 2.47, 3.63, 1.63, 2.83, 2.54, 1.45, 2.27,
       1.9 , 1.11, 3.07, 2.46, 2.38, 1.55, 2.56, 1.96, 3.67, 3.35, 1.65,
       3.53, 1.27, 1.65, 2.81, 5.2 , 2.85, 2.77, 1.82, 2.8 , 2.5 , 3.32,
       1.79, 1.24, 2.51, 2.21, 2.83, 2.09, 2.54, 4.14, 2.45, 1.57, 1.28,
       0.85, 1.04, 2.64, 2.56, 1.52, 2.43, 2.37, 2.06, 2.42, 3.36, 2.86,
       2.47, 3.57, 3.11, 2.75, 2.53, 2.05, 0.75, 3.58, 3.13, 2.82, 1.91,
       1.71, 2.09, 2.01, 4.05, 3.02, 2.99, 3.01, 1.65, 3.14, 4.22, 2.67,
       3.2 , 2.21, 1.97, 1.65, 1.39, 2.87, 1.52, 2.81, 3.45, 2.77, 3.48,
       3.3 , 1.59, 2.03, 3.79, 2.49, 4.65, 3.55, 3.15, 1.95, 2.69, 0.86,
       3.11, 3.69, 1.71, 1.82, 4.51, 2.57, 2.09, 2.35, 2.69, 1.65, 2.83,
       2.13, 2.15, 1.53, 2.49, 2.37, 1.85, 1.9 , 2.65, 2.75, 2.48, 2.7 ,
       1.49, 1.87, 1.03, 3.33, 2.71, 3.5 , 4.26])

We can transform the continuous target variable (house price) into the binary variable (house price range) according to the following rule.
|price range|category|label|
|:--:|:--:|:--:|
|$y\leq 2.5$|low|0|
|$y>2.5$|high|1|

In [12]:
y_ = np.zeros(row_num, dtype="int")
y_[y<=2.5] = 0
y_[y>2.5] = 1
y_

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1])

### Step 2: Data Preprocessing

The values of features X1-X6 are in different scales. The feature in a large scale would have a huge influence on label prediction. We shall normalize the values of different features into a uniform scale to balance the contributions of different features to label prediction. Here we use the [MinMaxScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html) to scale the feature values into the range of $[0,1]$. Another choice for feature normalization is [StandardScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html).

In [13]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X)
X = scaler.transform(X)

In [14]:
X

array([[0.27292576, 0.73059361, 0.00951267, 1.        , 0.61694135,
        0.71932284],
       [0.27292576, 0.44520548, 0.04380939, 0.9       , 0.5849491 ,
        0.71145137],
       [1.        , 0.30365297, 0.08331505, 0.5       , 0.67123122,
        0.75889584],
       ...,
       [0.63646288, 0.42922374, 0.05686115, 0.7       , 0.57149782,
        0.71522536],
       [0.36353712, 0.18493151, 0.0125958 , 0.5       , 0.42014057,
        0.72395946],
       [0.90938865, 0.14840183, 0.0103754 , 0.9       , 0.51211827,
        0.75016174]])

### Step 3: Train-Test Split

We randomly split the data $X$ and $y$ into training and test sets with the ratio $1:1$.

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y_, test_size=0.5, random_state=0)

### Step 4: House Price Range Prediction with Gaussian Process Classification

Read [Scikit-Learn's GaussianProcessClassifier API](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessClassifier.html), and implement the Gaussian process classification model with RBF kernel $k_{\mathrm{SE}}\left(\mathbf{x}_{i}, \mathbf{x}_{j}\right)=\sigma_f^{2} \exp \left(-\frac{1}{2 \ell^{2}}\left\|\mathbf{x}_{i}-\mathbf{x}_{j}\right\|_2^{2}\right)$.

**Task 1**: Implement the Gaussian process classification model with the hyperparameter setting: signal variance $\sigma_f^{2}=1.5$, length-scale $\ell=1.5$. Keep the hyperparameters fixed when fitting the model.

In [16]:
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF, ConstantKernel
# Train the Gaussian process classifier with the training data (X_train and y_train)
##: Write your code here
kernel = ConstantKernel(constant_value=1.5) * RBF(length_scale=1.5)

gpc = GaussianProcessClassifier(
    kernel=kernel,
    optimizer=None,
    random_state=0
)

gpc.fit(X_train, y_train)

GaussianProcessClassifier(kernel=1.22**2 * RBF(length_scale=1.5),
                          optimizer=None, random_state=0)

In [17]:
# Predict the labels of test data
##: Write your code 
y_pred = gpc.predict(X_test)
y_pred

array([1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0])

In [18]:
# Compare the ground-truth and predicted labels
##: Write your code here
pd.DataFrame({
    "Ground Truth": y_test,
    "Predicted": y_pred
})

     Ground Truth  Predicted
0               1          1
1               0          0
2               1          1
3               0          0
4               1          1
..            ...        ...
202             0          1
203             0          0
204             0          1
205             1          1
206             0          0

[207 rows x 2 columns]

Compute the accuracy score as an evaluation of the trained GaussianProcessClassifier model.

In [19]:
##: Write your code here
acc = gpc.score(X_test, y_test)
print("Accuracy:", acc)

Accuracy: 0.8405797101449275

In [20]:
# Print the log marginal likehood value of the fitted model
##: Write your code here
lml_value = gpc.log_marginal_likelihood_value_
print("Log Marginal Likelihood:", gpc.log_marginal_likelihood_value_)

Log Marginal Likelihood: -110.8489352425093

**Task 2**: Use [GaussianProcessClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessClassifier.html)'s log marginal likelihood value to select the best hyperparameter setting when signal variance $\sigma_f^2$ varies in the set $\{1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5\}$, and length-scale $\ell$ varies in $\{1, 2, 3, 4, 5\}$. Write a grid search program to do model selection, do not use [GaussianProcessClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessClassifier.html)'s automatic hyperparameter optimizer, report the best hyperparameter setting as well as the corresponding model's prediction performance.

In [21]:
# Use grid search to find the best hyperparameter setting
##: Write your code here
sigma_f2_values = [1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]
length_scale_values = [1, 2, 3, 4, 5]

best_lml = -np.inf
best_model = None
best_params = None

for sf in sigma_f2_values:
    for l in length_scale_values:

        kernel = ConstantKernel(sf) * RBF(l)

        gpc_model = GaussianProcessClassifier(
            kernel=kernel,
            optimizer=None,
            random_state=0
        )

        gpc_model.fit(X_train, y_train)

        lml = gpc_model.log_marginal_likelihood_value_

        if lml > best_lml:
            best_lml = lml
            best_model = gpc_model
            best_params = {"sigma_f2": sf, "length_scale": l}

In [22]:
# Predict the labels of test data
##: Write your code here
y_pred_best = best_model.predict(X_test)
y_pred_best

array([1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0])

In [23]:
# Compare the ground-truth and predicted labels
##: Write your code here
pd.DataFrame({
    "Ground Truth": y_test,
    "Predicted": y_pred_best
})

     Ground Truth  Predicted
0               1          1
1               0          0
2               1          1
3               0          0
4               1          1
..            ...        ...
202             0          1
203             0          0
204             0          1
205             1          1
206             0          0

[207 rows x 2 columns]

Compute the accuracy score as an evaluation of the selected best GaussianProcessClassifier model.

In [24]:
##: Write your code here
acc_best =best_model.score(X_test, y_test)
print("Best Accuracy:", acc_best)

Best Accuracy: 0.8454106280193237

In [25]:
# Print the best model's log marginal likehood value
##: Write your code here
lml = best_model.log_marginal_likelihood_value_
print("Best Log Marginal Likelihood:", lml)

Best Log Marginal Likelihood: -92.90830172524886

In [26]:
# Print the best model's hyperparameter setting
##: Write your code here
print("Best hyperparameters:", best_params)

Best hyperparameters: {'sigma_f2': 5, 'length_scale': 1}

**Task 3**: Use [GaussianProcessClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessClassifier.html)'s automatic hyperparameter optimizer to find the best hyperparameter setting when $\sigma_f^2$ and $\ell$ both vary in the range $[1,5]$. Report the best hyperparameter setting as well as the corresponding model's prediction performance.

In [27]:
# Train the Gaussian process classifier with the activated hyperparameter optimizer
##: Write your code here
kernel = ConstantKernel(constant_value=1.5, constant_value_bounds=(1, 5)) * RBF(length_scale=1.5, length_scale_bounds=(1, 5))

gpc_opt = GaussianProcessClassifier(
    kernel=kernel,
    random_state=0   
)

gpc_opt.fit(X_train, y_train)

GaussianProcessClassifier(kernel=1.22**2 * RBF(length_scale=1.5),
                          random_state=0)

In [28]:
# Predict the labels of test data
##: Write your code here
y_pred_opt = gpc_opt.predict(X_test)
y_pred_opt

array([1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0])

In [29]:
# Compare the ground-truth and predicted labels
##: Write your code here
pd.DataFrame({
    "Ground Truth": y_test,
    "Predicted": y_pred_opt
})

     Ground Truth  Predicted
0               1          1
1               0          0
2               1          1
3               0          0
4               1          1
..            ...        ...
202             0          1
203             0          0
204             0          1
205             1          1
206             0          0

[207 rows x 2 columns]

Compute the accuracy score as an evaluation of the optimized GaussianProcessClassifier model.

In [30]:
##: Write your code here
acc = gpc_opt.score(X_test, y_test)
print("Optimized Accuracy:", acc)

Optimized Accuracy: 0.8454106280193237

In [31]:
# Print the log marginal likelihood value of the optimized model
##: Write your code here
lml = gpc_opt.log_marginal_likelihood_value_
print("Optimized LML:", lml)

Optimized LML: -92.90830172524886

In [32]:
# Print the optimized hyperparameters
##: Write your code here
print("Signal variance:", gpc_opt.kernel_.k1.constant_value)
print("Length-scale:", gpc_opt.kernel_.k2.length_scale)

Signal variance: 4.999999999999999
Length-scale: 1.0

**Futher Exploration (Optional)**:
+ Choose [DotProduct](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.kernels.DotProduct.html) as the kernel function, evaluate the model's performance with the default kernel hyperparameter setting, and use grid search and [GaussianProcessClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessClassifier.html)'s hyperparameter optimizer to find the best hyperparameter setting.

In [33]:
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import DotProduct

kernel = DotProduct()

gpc_dot = GaussianProcessClassifier(
    kernel=kernel,
    random_state=0
)

gpc_dot.fit(X_train, y_train)

# predict
y_pred_dot = gpc_dot.predict(X_test)

# Accuracy
print("DotProduct (default) Accuracy:", gpc_dot.score(X_test, y_test))

# LML
print("DotProduct LML:", gpc_dot.log_marginal_likelihood_value_)

DotProduct (default) Accuracy: 0.8260869565217391
DotProduct LML: -106.57491985290547

In [34]:
sigma0_values = [0.1, 0.5, 1, 2, 5]

best_lml = -np.inf
best_model_dot = None
best_params_dot = None

for s in sigma0_values:

    kernel = DotProduct(sigma_0=s)

    model = GaussianProcessClassifier(
        kernel=kernel,
        optimizer=None,
        random_state=0
    )

    model.fit(X_train, y_train)

    lml = model.log_marginal_likelihood_value_

    if lml > best_lml:
        best_lml = lml
        best_model_dot = model
        best_params_dot = {"sigma_0": s}
        
print("Best DotProduct params:", best_params_dot)
print("Best DotProduct Accuracy:", best_model_dot.score(X_test, y_test))
print("Best DotProduct LML:", best_lml)

Best DotProduct params: {'sigma_0': 2}
Best DotProduct Accuracy: 0.8260869565217391
Best DotProduct LML: -106.59714770288198

In [35]:
kernel = DotProduct(
    sigma_0=1.0,
    sigma_0_bounds=(0.1, 5)
)

gpc_dot_opt = GaussianProcessClassifier(
    kernel=kernel,
    random_state=0
)

gpc_dot_opt.fit(X_train, y_train)

# predict
y_pred_opt = gpc_dot_opt.predict(X_test)

# Accuracy
print("Optimized DotProduct Accuracy:", gpc_dot_opt.score(X_test, y_test))

# LML
print("Optimized DotProduct LML:", gpc_dot_opt.log_marginal_likelihood_value_)

print("Optimized sigma_0:", gpc_dot_opt.kernel_.sigma_0)

Optimized DotProduct Accuracy: 0.8260869565217391
Optimized DotProduct LML: -106.57491985290547
Optimized sigma_0: 1.6599488427723301